image:
  repository: sapcc/node-problem-detector
  tag: v0.8.5

resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 20m
    memory: 20Mi

# Expose additional Prometheus metrics directly.
prometheus:
  enabled: false
  address: 0.0.0.0
  port: 20257
  targets: kubernetes

# Additional system log monitors.
systemLogMonitors:
  - kernel-monitor.json

# Additional custom plugin monitors.
customPluginMonitors:
  # - bridge-monitor.json

# Additional volume mounts from host.
additionalHostVolumeMounts: []
  # Required by the bridge monitor.
  #- name: hostproc
  #  hostPath: /proc
  #  mountPath: /host/proc
  #  readOnly: true
