dependencies:
  - name: prometheus-operator
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 8.16.1

  - name: event-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2

  - name: fluent-bit
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 2.7.2

  - name: kube-state-metrics
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 2.4.1

  - name: k8s-secrets-certificate-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.0

  - name: ntp-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.1.0

  - name: oomkill-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2

  - name: prometheus-node-exporter
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.8.0

  - name: prometheus-server
    repository: https://charts.eu-de-2.cloud.sap
    version: 3.3.3

  - name: prometheus-kubernetes-rules
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.17

  - name: grafana
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 4.0.4

  - name: ping-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.0
    condition: ping-exporter.enabled

  - name: grafana-dashboards-kubernetes 
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.4

  - name: kubernikus-monitoring
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.1.4

  - name: prometheus-crds
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.0

  - name: watchcache-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2

  - name: loki
    repository: https://grafana.github.io/loki/charts
    version: 0.20.0
    condition: loki.enabled

  - name: promtail
    repository: https://grafana.github.io/loki/charts
    version: 0.15.0
    condition: loki.enabled
