dependencies:
  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.41.3

  - name: node-problem-detector
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.2.2

  - name: vice-president
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.1.4

  - name: disco
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.3.6

  - name: prometheus-crds
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.0

  - name: cc-rbac
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.0

  - name: manila-provisioner
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.0
